{% set name = "riverrem" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenTopography/RiverREM/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 125b9646d7dfbe980da9a0680419756385c4da2e89ae0b0a98819a9d548f6a1a

build:
  noarch: python
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - gdal
    - scipy
    - osmnx
    - dataclasses
    - seaborn
    - scipy >=1.6.0
    - shapely
    - pandas
    - bottleneck
    - numexpr
    - geopandas
    - dataclasses
    - seaborn
    - toml

test:
  imports:
    - riverrem
    - riverrem.RasterViz
    - riverrem.REMMaker

about:
  home: https://github.com/OpenTopography/RiverREM
  summary: 'Make river relative elevation models (REM) and REM visualizations from an input digital elevation model (DEM).'
  description: |
    RiverREM is a Python package for automatically generating river relative elevation model (REM) visualizations 
    from nothing but an input digital elevation model (DEM). The package uses the OpenStreetMap API to retrieve 
    river centerline geometries over the DEM extent. Interpolation of river elevations is automatically handled 
    using a sampling scheme based on raster resolution and river sinuosity to create striking high-resolution 
    visualizations without interpolation artefacts straight out of the box and without additional manual steps. 
    The package also contains a helper class for creating DEM raster visualizations.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  doc_url: https://opentopography.github.io/RiverREM/
  dev_url: https://github.com/OpenTopography/RiverREM/

extra:
  recipe-maintainers:
    - klarrieu
