{% set name = "riverrem" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenTopography/RiverREM/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c003c6495a74c12a538aa5709c6bede4441c1af11c2cdecfe4cf6f2c100bdd98

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - gdal >=3.1.4
    - osmnx
    - dataclasses
    - seaborn
    - scipy >=1.6.0
    - shapely
    - pandas
    - requests
    - geopandas
    - bottleneck
    - numexpr

test:
  imports:
    - riverrem
    - riverrem.RasterViz
    - riverrem.REMMaker
  source-files:
    - tests/smith_SRTM.tif
    - tests/test_local.py
    - tests/test_url.py

about:
  home: https://github.com/OpenTopography/RiverREM
  summary: 'Make river relative elevation models (REM) and REM visualizations from an input digital elevation model (DEM).'
  description: |
    RiverREM is a Python package for automatically generating river relative elevation model (REM) visualizations 
    from nothing but an input digital elevation model (DEM). The package uses the OpenStreetMap API to retrieve 
    river centerline geometries over the DEM extent. Interpolation of river elevations is automatically handled 
    using a sampling scheme based on raster resolution and river sinuosity to create striking high-resolution 
    visualizations without interpolation artefacts straight out of the box and without additional manual steps. 
    The package also contains a helper class for creating DEM raster visualizations.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  doc_url: https://opentopography.github.io/RiverREM/
  dev_url: https://github.com/OpenTopography/RiverREM/

extra:
  recipe-maintainers:
    - klarrieu
